import Vue from 'vue'
import { MLInstaller, MLCreate, MLanguage } from 'vue-multilanguage'

Vue.use(MLInstaller)

export default new MLCreate({
    initial: 'en',
    save: true, // process.env.NODE_ENV === 'production',
    languages: [
        new MLanguage('en').create({
            italian: "Italian",
            english: "English",
            french: "French",
            spanish: "Spanish",
            portuguese: "Portuguese",
            storyTeller: "Story Teller",
            player: "Player",
            storyTellerLoginSubtitle: "Manage yuor chronicle an invite your players",
            playerLoginSubtitle: "Create your characters and join chronicles",
            loginButton: "Sing in with Google",
            publicStory: "Public Story",
            privateStory: "Privite Story",
            sessionsTimeline: "Sessions Timeline",
            joinChronicle: "Join the Chronicle",
            pendingInvitation: "Pending Invitation",
            invitationSent: "Invitation sent",
            invitationDeleted: "Invitation deleted",
            general: "General",
            refuges: "Refuges",
            refuge: "Refuge",
            updateAttachment: "Update attachment",
            createNewAttachment: "Create new attachment",
            createNewCharacter: "Create new character",
            createNewStory: "Create new story",
            createNewChronicle: "Create new chronicle",
            createNewPlace: "Create new place",
            updatePlace: "Update place",
            addDiscipline: "Add Discipline",
            disciplines: "Disciplines",
            saveSuccessfully: "Save successfully",
            fightStarted: "Fight started - auto-save enable",
            fightEnded: "Fight ended - auto-save disable",
            main: "Main",
            globalNote: "Global Note",
            experiencePoints: "Experience Points",
            playerNote: "Player Note",
            storyTellerNote: "Story-teller Note",
            dateFormat: "MMMM Do YYYY",
            createNewCoterie: "Create new Coterie / Pack",
            shortDescription: "Short description",
            noChronicle: "No Chronicle created",
            needCreation: "You have to create a Chronicle to start your story telling",

            // button label
            close: "Close",
            open: "Open",
            edit: "Edit",
            delete: "Delete",
            fight: "Fight",
            endFight: "End Fight",
            kill: "Kill",
            logout: "Logout",
            details: "Details",
            createStory: "Create Story",
            dismiss: "Dismiss",
            confirm: "Confirm",
            save: "Save",
            setOngoingStory: "Set as on going story",
            invitePlayer: "Invite player",
            createCoterie: "Create Coterie / Pack",
            fullScreen: "Full screen",
            send: "Send",
            complete: "Complete",
            undo: "Undo",
            createChronicle: "Create new Chronicle",
            resume: "Resume",
            add: "Add",
            start: "Start",
            startSession: "Start Session",
            sessionDetails: "Session Details",
            sessionOnGoing: "Session on going",
            endStory: "End Story",
            onGoing: "On Going",
            cancel: "Cancel",
            warning: "Warning",

            // input label
            selectImage: "Select image",
            playerVisibility: "Player Visibility",
            name: "Name",
            enterAnAddress: "Enter an address",
            address: "Address",
            noResultFound: "No result found",

            // icon tooltip
            dashboard: "Dashboard",
            stories: "Stories",
            players: "Players",
            coterie: "Coterie / Pack",
            attachments: "Attachments",
            places: "Places",
            session: "Session",
            characters: "Characters",

            // sheet label
            characteristics: "Characteristics",
            background: "Background",
            story: "Story",
            history: "History",
            generation: "Generation",
            clan: "Clan",
            sire: "Sire",
            lastUpdate: "Last Update",
            startingExperiencePoints: "Starting Experience Points",
            mainInformation: "Main Information",
            concept: "Concept",
            predator: "Predator",
            ambition: "Ambition",
            desire: "Desire",
            mortalLife: "Mortal Life",
            trueAge: "True age",
            apparentAge: "Apparent age",
            dateOfBirth: "Date of birth",
            dateOfDeath: "Date of death",
            academics: "Academics",
            animalKen: "Animal Ken",
            athletics: "Athletics",
            awareness: "Awareness",
            brawl: "Brawl",
            carisma: "Carism",
            composure: "Composure",
            craft: "Craft",
            dexterity: "Dexterity",
            drive: "Drive",
            etiquette: "Etiquette",
            finance: "Finance",
            firearms: "Firearms",
            insight: "Insight",
            intelligence: "Intelligence",
            intimidation: "Intimidation",
            investigation: "Investigation",
            larceny: "Larceny",
            leadership: "Leadership",
            manipulation: "Manipulation",
            medicine: "Medicine",
            melee: "Melee",
            occult: "Occult",
            performance: "Performance",
            persuasion: "Persuasion",
            politics: "Politics",
            resolve: "Resolve",
            science: "Science",
            stamina: "Stamina",
            stealth: "Stealth",
            streetwise: "Streetwise",
            strength: "Strength",
            subterfuge: "Subterfuge",
            survival: "Survival",
            technology: "Technology",
            wits: "Wits",
            health: "Health",
            willPower: "Will Power",
            humanity: "Humanity",
            bloodPotency: "Blood Potence",
            hunger: "Hunger",
            physical: "Physical",
            mental: "Mental",
            social: "Social",
            resonance: "Resonance",
            special: "special",

            // messages
            chronicleSuccessCreation: "Chronicle successfully created",
            sessionStarted: "Session started",
            areYouSure: "Are you sure?",
            chronicleDeleted: "Chronicle successfully deleted",
            charactersWillBeDeleted: "All the characters connected will be deleted",
            dataWillBeDeleted: "All the data connected will be deleted",
            confirmStartStory: "Do you really want to start this story?",
            confirmEndStory: "Do you really want to end this story?",
            confirmDelete: "Do you really want to delete {0}?",
            confirmInvitationDelete: "Do you really want to delete invitation sent to {0}?",
            confirmDeleteDiscipline: "Do you really want remove {0}?",
        }),

        new MLanguage('it').create({
            italian: "Italiano",
            english: "Inglese",
            french: "French",
            spanish: "Spagnolo",
            portuguese: "Portoghese",
            storyTeller: "Narratore",
            player: "Giocatore",
            storyTellerLoginSubtitle: "Gestisci le tue cronache e invita i tuoi giocatori",
            playerLoginSubtitle: "Crea il tuo personaggio e partecipa alle cronache",
            loginButton: "Accedi con Google",
            publicStory: "Storia Pubblica",
            privateStory: "Storia Privata",
            sessionsTimeline: "Cronologia sessioni",
            joinChronicle: "Partecipa alla cronaca",
            pendingInvitation: "Inviti in attesa",
            invitationSent: "Invito inviato",
            invitationDeleted: "Invito eliminato",
            general: "Generali",
            refuges: "Rifugi",
            refuge: "Rifugio",
            updateAttachment: "Aggiorna allegato",
            createNewAttachment: "Crea nuovo allegato",
            createNewCharacter: "Crea nuovo personaggio",
            createNewStory: "Crea nuova storia",
            createNewChronicle: "Crea nuova cronaca",
            createNewPlace: "Crea nuovo luogo",
            updatePlace: "Aggiorna luogo",
            addDiscipline: "Aggiungi Disciplina",
            disciplines: "Discipline",
            saveSuccessfully: "Salvataggio avvenuto con successo",
            fightStarted: "Combattimento iniziato - auto-salvataggio abilitato",
            fightEnded: "Combattimento terminato - auto-salvataggio disabilitato",
            main: "Principale",
            globalNote: "Note Globali",
            experiencePoints: "Punti Esperienza",
            playerNote: "Note Giocatore",
            storyTellerNote: "Note Narratore",
            dateFormat: "Do MMMM YYYY",
            createNewCoterie: "Crea nuova Coterie / Pack",
            shortDescription: "Breve descrizione",
            noChronicle: "Nessuna cronaca creata",
            needCreation: "E' necessario creare una cronaca per iniziare la tua narrazione",

            // button label
            close: "Chiudi",
            open: "Apri",
            edit: "Modifica",
            delete: "Elimina",
            fight: "Combatti",
            endFight: "Termina",
            kill: "Uccidi",
            logout: "Esci",
            details: "Dettagli",
            createStory: "Crea Storia",
            dismiss: "Annulla",
            confirm: "Conferma",
            save: "Salva",
            setOngoingStory: "Imposta come storia attiva",
            invitePlayer: "Invita giocatore",
            createCoterie: "Crea Coterie / Pack",
            fullScreen: "Schermo intero",
            send: "Invia",
            complete: "Complete",
            undo: "Annulla",
            createChronicle: "Crea una nuova cronaca",
            resume: "Resume",
            add: "Aggiungi",
            start: "Inizia",
            startSession: "Inizia Session",
            sessionDetails: "Dettagli Sessione",
            sessionOnGoing: "Session attiva",
            endStory: "Termina storia",
            onGoing: "Attiva",
            cancel: "Cancella",
            warning: "Attenzione",

            // input label
            selectImage: "Seleziona immagine",
            playerVisibility: "Visibilità giocatori",
            name: "Nome",
            enterAnAddress: "Inserisci un indirizzo",
            address: "Indirizzo",
            noResultFound: "Nessun risultato trovato",

            // icon tooltip
            dashboard: "Riepilogo",
            stories: "Storie",
            players: "Giocatori",
            coterie: "Coterie / Pack",
            attachments: "Allegati",
            places: "Luoghi",
            session: "Sessione",
            characters: "Personaggi",

            // sheet label
            characteristics: "Caratteristiche",
            background: "Passato",
            story: "Storia",
            history: "Cronologia",
            generation: "Generazione",
            clan: "Clan",
            sire: "Sire",
            lastUpdate: "Ultimo aggiornamento",
            startingExperiencePoints: "Punti Esperienza Iniziali",
            mainInformation: "Informazioni Principali",
            concept: "Concetto",
            predator: "Predatore",
            ambition: "Ambizione",
            desire: "Desiderio",
            mortalLife: "Vita Mortale",
            trueAge: "Età vera",
            apparentAge: "Età apparente",
            dateOfBirth: "Data di nasciata",
            dateOfDeath: "Data di morte",
            academics: "Accademiche",
            animalKen: "Addestrare animali",
            athletics: "Atletica",
            awareness: "Conoscienza",
            brawl: "Rissa",
            carisma: "Carisma",
            composure: "Aspetto",
            craft: "Manualità",
            dexterity: "Destrezza",
            drive: "Guidare",
            etiquette: "Galteo",
            finance: "Finanza",
            firearms: "Armi da fuoco",
            insight: "Empatia",
            intelligence: "Intelligenza",
            intimidation: "Intimidire",
            investigation: "Investigare",
            larceny: "Furtività",
            leadership: "Comando",
            manipulation: "Manipolazione",
            medicine: "Medicina",
            melee: "Mischia",
            occult: "Occulto",
            performance: "Espressione Artistica",
            persuasion: "Persuasione",
            politics: "Politica",
            resolve: "Prontezza",
            science: "Scienza",
            stamina: "Costituzione",
            stealth: "Muoversi silenziosamente",
            streetwise: "Conoscenza della strada",
            strength: "Forza",
            subterfuge: "Sotterfugio",
            survival: "Sopravvivenza",
            technology: "Tecnologia",
            wits: "Percezione",
            health: "Salute",
            willPower: "Forza di volontà",
            humanity: "Umanità",
            bloodPotency: "Potenza del sangue",
            hunger: "Fame",
            physical: "Fisiche",
            mental: "Mentali",
            social: "Sociali",
            resonance: "Risonanza",
            special: "speciale",

            // messages
            chronicleSuccessCreation: "Cronaca creata con successo",
            sessionStarted: "Session avviata",
            areYouSure: "Sei sicuro?",
            chronicleDeleted: "Cronaca eliminata con successo",
            charactersWillBeDeleted: "Tutti i personaggi collegati verranno eliminati",
            dataWillBeDeleted: "Tutte le informazioni collegate verranno eliminate",
            confirmStartStory: "Vuoi davvero avviare questa storia?",
            confirmEndStory: "Vuoi davvero terminare questa storia?",
            confirmDelete: "Vuoi davvero eliminare {0}?",
            confirmInvitationDelete: "Sei sicuro voler eliminare l'invito inviato a {0}?",
            confirmDeleteDiscipline: "Vuoi davvero eliminare {0}?",
        }),

        new MLanguage('fr').create({
            italian: "Italian",
            english: "English",
            french: "French",
            spanish: "Spanish",
            portuguese: "Portuguese",
            storyTeller: "Story Teller",
            player: "Player",
            storyTellerLoginSubtitle: "Manage yuor chronicle an invite your players",
            playerLoginSubtitle: "Create your characters and join chronicles",
            loginButton: "Sing in with Google",
            publicStory: "Public Story",
            privateStory: "Privite Story",
            sessionsTimeline: "Sessions Timeline",
            joinChronicle: "Join the Chronicle",
            pendingInvitation: "Pending Invitation",
            invitationSent: "Invitation sent",
            invitationDeleted: "Invitation deleted",
            general: "General",
            refuges: "Refuges",
            refuge: "Refuge",
            updateAttachment: "Update attachment",
            createNewAttachment: "Create new attachment",
            createNewCharacter: "Create new character",
            createNewStory: "Create new story",
            createNewChronicle: "Create new chronicle",
            createNewPlace: "Create new place",
            updatePlace: "Update place",
            addDiscipline: "Add Discipline",
            disciplines: "Disciplines",
            saveSuccessfully: "Save successfully",
            fightStarted: "Fight started - auto-save enable",
            fightEnded: "Fight ended - auto-save disable",
            main: "Main",
            globalNote: "Global Note",
            experiencePoints: "Experience Points",
            playerNote: "Player Note",
            storyTellerNote: "Story-teller Note",
            dateFormat: "MMMM Do YYYY",
            createNewCoterie: "Create new Coterie / Pack",
            shortDescription: "Short description",
            noChronicle: "No Chronicle created",
            needCreation: "You have to create a Chronicle to start your story telling",

            // button label
            close: "Close",
            open: "Open",
            edit: "Edit",
            delete: "Delete",
            fight: "Fight",
            endFight: "End Fight",
            kill: "Kill",
            logout: "Logout",
            details: "Details",
            createStory: "Create Story",
            dismiss: "Dismiss",
            confirm: "Confirm",
            save: "Save",
            setOngoingStory: "Set as on going story",
            invitePlayer: "Invite player",
            createCoterie: "Create Coterie / Pack",
            fullScreen: "Full screen",
            send: "Send",
            complete: "Complete",
            undo: "Undo",
            createChronicle: "Create new Chronicle",
            resume: "Resume",
            add: "Add",
            start: "Start",
            startSession: "Start Session",
            sessionDetails: "Session Details",
            sessionOnGoing: "Session on going",
            endStory: "End Story",
            onGoing: "On Going",
            cancel: "Cancel",
            warning: "Warning",

            // input label
            selectImage: "Select image",
            playerVisibility: "Player Visibility",
            name: "Name",
            enterAnAddress: "Enter an address",
            address: "Address",
            noResultFound: "No result found",

            // icon tooltip
            dashboard: "Dashboard",
            stories: "Stories",
            players: "Players",
            coterie: "Coterie / Pack",
            attachments: "Attachments",
            places: "Places",
            session: "Session",
            characters: "Characters",

            // sheet label
            characteristics: "Characteristics",
            background: "Background",
            story: "Story",
            history: "History",
            generation: "Generation",
            clan: "Clan",
            sire: "Sire",
            lastUpdate: "Last Update",
            startingExperiencePoints: "Starting Experience Points",
            mainInformation: "Main Information",
            concept: "Concept",
            predator: "Predator",
            ambition: "Ambition",
            desire: "Desire",
            mortalLife: "Mortal Life",
            trueAge: "True age",
            apparentAge: "Apparent age",
            dateOfBirth: "Date of birth",
            dateOfDeath: "Date of death",
            academics: "Academics",
            animalKen: "Animal Ken",
            athletics: "Athletics",
            awareness: "Awareness",
            brawl: "Brawl",
            carisma: "Carism",
            composure: "Composure",
            craft: "Craft",
            dexterity: "Dexterity",
            drive: "Drive",
            etiquette: "Etiquette",
            finance: "Finance",
            firearms: "Firearms",
            insight: "Insight",
            intelligence: "Intelligence",
            intimidation: "Intimidation",
            investigation: "Investigation",
            larceny: "Larceny",
            leadership: "Leadership",
            manipulation: "Manipulation",
            medicine: "Medicine",
            melee: "Melee",
            occult: "Occult",
            performance: "Performance",
            persuasion: "Persuasion",
            politics: "Politics",
            resolve: "Resolve",
            science: "Science",
            stamina: "Stamina",
            stealth: "Stealth",
            streetwise: "Streetwise",
            strength: "Strength",
            subterfuge: "Subterfuge",
            survival: "Survival",
            technology: "Technology",
            wits: "Wits",
            health: "Health",
            willPower: "Will Power",
            humanity: "Humanity",
            bloodPotency: "Blood Potence",
            hunger: "Hunger",
            physical: "Physical",
            mental: "Mental",
            social: "Social",
            resonance: "Resonance",
            special: "special",

            // messages
            chronicleSuccessCreation: "Chronicle successfully created",
            sessionStarted: "Session started",
            areYouSure: "Are you sure?",
            chronicleDeleted: "Chronicle successfully deleted",
            charactersWillBeDeleted: "All the characters connected will be deleted",
            dataWillBeDeleted: "All the data connected will be deleted",
            confirmStartStory: "Do you really want to start this story?",
            confirmEndStory: "Do you really want to end this story?",
            confirmDelete: "Do you really want to delete {0}?",
            confirmInvitationDelete: "Do you really want to delete invitation sent to {0}?",
            confirmDeleteDiscipline: "Do you really want remove {0}?",
        }),
    ]
})